### ISSUE TITLE
Task and contest YAML configuration files lack documentation

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#1154]
## Issue template

**Description:** Task and contest configuration file lack documentation

I am not able to find a complete specification of the configuration files for tasks and contests in YAML format (`italy_yaml`).

Looking at the examples in the test contest repository - such as [`con_test/batch/task.yaml`](https://github.com/cms-dev/con_test/blob/master/batch/task.yaml) - there is no information.

Here's an example of a minimal configuration file for a task:
```yaml
name: "sum"
title: "Sum of two numbers"
time_limit: 1
memory_limit: 8
diff: 1
n_input: 10
public_testcases: "0,1,2,3,4,5,6,7,8,9"
token_mode: disabled
```

I would like to be able to help with the documentation, but I need some pointers on where to write it.
